In [2]:
import numpy as np


# creation of empty numpy

In [3]:
emp=np.empty([2,2])
print(emp)

[[2.12199579e-314 1.00794800e-311]
 [5.92878775e-321 6.95187041e-310]]


In [6]:
emp1=np.empty(shape=[3,3])
emp1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# creating of zeros 

In [15]:
z=np.zeros(shape=[2,3],dtype='int32')
print(z)


[[0 0 0]
 [0 0 0]]


# creating of array with one value

In [22]:
o=np.ones(shape=[3,3],dtype='int64')
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# using of full

In [30]:
f=np.full(shape=[4,4],fill_value=5)
print(f)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [33]:
f=np.full(shape=[4,4],fill_value=5,dtype='float64')
print(f)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


# identity matrix

In [34]:
i=np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
i=np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# RGB values of image  store in numpy.

# np.arange()

In [40]:
a=np.arange(1,10,dtype='float64')
print(a)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
q=np.arange(1,100)
print(q)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [44]:
x=np.arange(1,20,2)
print(x)
x=x.reshape([2,5])
print(x)

[ 1  3  5  7  9 11 13 15 17 19]
[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [69]:
x=np.arange(2,21,2)
print(x)
x=x.reshape([5,2])
print(x)

[ 2  4  6  8 10 12 14 16 18 20]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


# np.linspace

In [60]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, s

In [64]:
m=np.linspace(5,20,10)
print(m)
print(len(m))

[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]
10
